In [2]:
pip install billboard.py

Collecting billboard.py
  Downloading billboard.py-7.0.0-py2.py3-none-any.whl (7.0 kB)
Requirement already satisfied: requests>=2.2.1 in /usr/local/lib/python3.7/dist-packages (from billboard.py) (2.23.0)
Requirement already satisfied: beautifulsoup4>=4.4.1 in /usr/local/lib/python3.7/dist-packages (from billboard.py) (4.6.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.2.1->billboard.py) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.2.1->billboard.py) (2021.10.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.2.1->billboard.py) (1.24.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.2.1->billboard.py) (3.0.4)
Installing collected packages: billboard.py
Successfully installed billboard.py-7.0.0

In [3]:
import billboard 
import pandas as pd

In [23]:
artists = []
year = 2021
for y in range(2022-2006):
    chart = billboard.ChartData('Top-Artists', year=year)
    cnt = 0
    for chr in chart:
        cnt += 1
        if chr.artist not in artists:
                artists.append(chr.artist)
        if cnt == 10:
            break
    
    year -= 1

len(artists)

80

In [24]:
def getData(type, data, artists, titles, year=None, date=None, label=None):
    if date==None:
        HotChart = billboard.ChartData(type, year=year)
    else:
        HotChart = billboard.ChartData(type, date=date)
    for hot in HotChart:
        if hot.title not in titles and hot.artist in artists:
                titles.append(hot.title)
                data.append({'Artist': hot.artist, 'Title': hot.title, 'Label': label})
    
    return data, titles

In [25]:
data = []
titles = []
year = 2021
for i in range(2022-2006):
    data, titles = getData('Hot-100-Songs', data, artists, titles, year, label=1)
    year -= 1

In [26]:
print(len(data))
print(len(artists))
print(len(titles))

403
80
403

In [28]:
dates = ['2021-12-01','2021-08-01','2021-04-01','2021-01-01',
        '2020-12-01','2020-08-01','2020-04-01','2020-01-01',
        '2019-12-01','2019-08-01','2019-04-01','2019-01-01',
        '2018-12-01','2018-08-01','2018-04-01','2018-01-01',
        '2017-12-01','2017-08-01','2017-04-01','2017-01-01',
        '2016-12-01','2016-08-01','2016-04-01','2016-01-01',
        '2015-12-01','2015-08-01','2015-04-01','2015-01-01',
        '2014-12-01','2014-08-01','2014-04-01','2014-01-01',
        '2013-12-01','2013-08-01','2013-04-01','2013-01-01',
        '2012-12-01','2012-08-01','2012-04-01','2012-01-01',
        '2011-12-01','2011-08-01','2011-04-01','2011-01-01',
        '2010-12-01','2010-08-01','2010-04-01','2010-01-01',
        '2009-12-01','2009-08-01','2009-04-01','2009-01-01',
        '2008-12-01','2008-08-01','2008-04-01','2008-01-01',
        '2007-12-01','2007-08-01','2007-04-01','2007-01-01',
        '2006-12-01','2006-08-01','2006-04-01','2006-01-01']
for date in dates:
    data, titles = getData('hot-100', data, artists, titles, date=date, label=0)

In [29]:
print(len(data))
print(len(artists))
print(len(titles))

809
80
809

In [30]:
df = pd.DataFrame(data)
df

             Artist                           Title  Label
0        The Weeknd                 Blinding Lights      1
1    Olivia Rodrigo                        Good 4 U      1
2    Olivia Rodrigo                 Drivers License      1
3         Lil Nas X  Montero (Call Me By Your Name)      1
4               BTS                          Butter      1
..              ...                             ...    ...
804    Gwen Stefani                       Luxurious      0
805         Rihanna    If It's Lovin' That You Want      0
806       Lil Wayne                         Fireman      0
807     Alicia Keys                     Unbreakable      0
808   Rascal Flatts                 Skin (Sarabeth)      0

[809 rows x 3 columns]

In [34]:
df[df['Artist']=='Justin Bieber']

            Artist                              Title  Label
21   Justin Bieber                             Anyone      1
39   Justin Bieber                              Yummy      1
129  Justin Bieber                      Love Yourself      1
130  Justin Bieber                              Sorry      1
138  Justin Bieber                  What Do You Mean?      1
221  Justin Bieber                          Boyfriend      1
328  Justin Bieber                           One Time      1
411  Justin Bieber                              Ghost      0
438  Justin Bieber                        Off My Face      0
439  Justin Bieber                             2 Much      0
441  Justin Bieber                        Deserve You      0
443  Justin Bieber                           Somebody      0
448  Justin Bieber  Rockin' Around The Christmas Tree      0
578  Justin Bieber                            Company      0
583  Justin Bieber                      I'll Show You      0
588  Justin Bieber                            Purpose      0
589  Justin Bieber                      Mark My Words      0
590  Justin Bieber               Life Is Worth Living      0
591  Justin Bieber                           Children      0
593  Justin Bieber                           Been You      0
596  Justin Bieber                     Get Used To It      0
600  Justin Bieber                              Trust      0
638  Justin Bieber                   All That Matters      0
682  Justin Bieber                          Mistletoe      0
718  Justin Bieber                            U Smile      0
730  Justin Bieber               One Less Lonely Girl      0
737  Justin Bieber                      Down To Earth      0
739  Justin Bieber                             Bigger      0

In [36]:
df[df['Artist']=='The Weeknd']

         Artist                             Title  Label
0    The Weeknd                   Blinding Lights      1
23   The Weeknd                    Take My Breath      1
32   The Weeknd                         Heartless      1
98   The Weeknd                  Call Out My Name      1
139  The Weeknd                         The Hills      1
145  The Weeknd                      In The Night      1
148  The Weeknd                Can't Feel My Face      1
160  The Weeknd  Earned It (Fifty Shades Of Grey)      1
481  The Weeknd                      In Your Eyes      0
482  The Weeknd                       Alone Again      0
483  The Weeknd                       After Hours      0
484  The Weeknd                    Scared To Live      0
485  The Weeknd                   Hardest To Love      0
487  The Weeknd                          Too Late      0
488  The Weeknd                         Snowchild      0
489  The Weeknd                    Escape From LA      0
490  The Weeknd                             Faith      0
491  The Weeknd       Repeat After Me (Interlude)      0
493  The Weeknd                 Until I Bleed Out      0
555  The Weeknd                          Reminder      0
561  The Weeknd                     Party Monster      0
564  The Weeknd                    Six Feet Under      0
577  The Weeknd                        Acquainted      0
619  The Weeknd                             Often      0
667  The Weeknd                      Wicked Games      0

In [35]:
df.shape

(809, 3)

In [38]:
df.to_csv('billboard.csv',index=False)

In [40]:
dataset = pd.read_csv('billboard.csv')
dataset

             Artist                           Title  Label
0        The Weeknd                 Blinding Lights      1
1    Olivia Rodrigo                        Good 4 U      1
2    Olivia Rodrigo                 Drivers License      1
3         Lil Nas X  Montero (Call Me By Your Name)      1
4               BTS                          Butter      1
..              ...                             ...    ...
804    Gwen Stefani                       Luxurious      0
805         Rihanna    If It's Lovin' That You Want      0
806       Lil Wayne                         Fireman      0
807     Alicia Keys                     Unbreakable      0
808   Rascal Flatts                 Skin (Sarabeth)      0

[809 rows x 3 columns]